// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VenueAxe.Data;

#nullable disable

namespace VenueAxe.Data.Migrations
{
    [DbContext(typeof(VenueAxeDbContext))]
    [Migration("20260909153017_AddTargetCellIndexToMatchThrow")]
    partial class AddTargetCellIndexToMatchThrow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppliedDiscountCode")
                        .HasColumnType("text");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BookingTypeId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomIntakeResponsesJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("DiscountAmountCents")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PaidAmountCents")
                        .HasColumnType("integer");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SquareOrderId")
                        .HasColumnType("text");

                    b.Property<string>("SquarePaymentId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalAmountCents")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingReference")
                        .IsUnique();

                    b.HasIndex("VenueId", "StartTime", "EndTime");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.BookingConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddonsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("BasePriceCents")
                        .HasColumnType("integer");

                    b.Property<string>("BookingTypesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CancellationPolicy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("DepositAmountCents")
                        .HasColumnType("integer");

                    b.Property<string>("DepositType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiscountRulesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EditorThemeJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("MaxPartySize")
                        .HasColumnType("integer");

                    b.Property<int>("MinPartySize")
                        .HasColumnType("integer");

                    b.Property<string>("PackagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PeakPriceCents")
                        .HasColumnType("integer");

                    b.Property<string>("PricingModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("SlotDurationsMinutes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TurnaroundBufferMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId")
                        .IsUnique();

                    b.ToTable("booking_configs", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.BookingLane", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LaneId")
                        .HasColumnType("uuid");

                    b.HasKey("BookingId", "LaneId");

                    b.HasIndex("LaneId");

                    b.ToTable("booking_lanes", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.GameMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("GameTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WinnerPlayerId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("game_matches", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Lane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LaneNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxThrowers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ScreenDeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("ScreenPairingCode")
                        .HasColumnType("text");

                    b.Property<string>("TabletDeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("TabletPairingCode")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "LaneNumber")
                        .IsUnique();

                    b.ToTable("lanes", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.LaneSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveRosterJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LaneId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("LaneId");

                    b.ToTable("lane_sessions", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.MatchThrow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClutchCalled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<double?>("NormalizedX")
                        .HasColumnType("double precision");

                    b.Property<double?>("NormalizedY")
                        .HasColumnType("double precision");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetCellIndex")
                        .HasColumnType("integer");

                    b.Property<string>("TargetZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThrowNumberInRound")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ThrownAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalThrowSequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("match_throws", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PlanTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("BrandingConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BusinessHoursJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeAccountId")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique();

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Waiver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGuardianSigning")
                        .HasColumnType("boolean");

                    b.Property<string>("MinorsCoveredJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SignatureImagePngBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignatureVectorSvg")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignerFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignerLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("VenueId", "SignerLastName", "SignerEmail");

                    b.ToTable("waivers", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.WaiverTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyTextMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("waiver_templates", (string)null);
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Booking", b =>
                {
                    b.HasOne("VenueAxe.Domain.Entities.Venue", "Venue")
                        .WithMany("Bookings")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.BookingConfig", b =>
                {
                    b.HasOne("VenueAxe.Domain.Entities.Venue", "Venue")
                        .WithOne("BookingConfig")
                        .HasForeignKey("VenueAxe.Domain.Entities.BookingConfig", "VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.BookingLane", b =>
                {
                    b.HasOne("VenueAxe.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingLanes")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenueAxe.Domain.Entities.Lane", "Lane")
                        .WithMany("BookingLanes")
                        .HasForeignKey("LaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Lane");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.GameMatch", b =>
                {
                    b.HasOne("VenueAxe.Domain.Entities.LaneSession", "Session")
                        .WithMany("Matches")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Lane", b =>
                {
                    b.HasOne("VenueAxe.Domain.Entities.Venue", "Venue")
                        .WithMany("Lanes")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.LaneSession", b =>
                {
                    b.HasOne("VenueAxe.Domain.Entities.Booking", "Booking")
                        .WithMany("LaneSessions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VenueAxe.Domain.Entities.Lane", "Lane")
                        .WithMany("Sessions")
                        .HasForeignKey("LaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Lane");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.MatchThrow", b =>
                {
                    b.HasOne("VenueAxe.Domain.Entities.GameMatch", "Match")
                        .WithMany("Throws")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.User", b =>
                {
                    b.HasOne("VenueAxe.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenueAxe.Domain.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tenant");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Venue", b =>
                {
                    b.HasOne("VenueAxe.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Venues")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Waiver", b =>
                {
                    b.HasOne("VenueAxe.Domain.Entities.Booking", "Booking")
                        .WithMany("Waivers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VenueAxe.Domain.Entities.WaiverTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VenueAxe.Domain.Entities.Venue", "Venue")
                        .WithMany("Waivers")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Template");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.WaiverTemplate", b =>
                {
                    b.HasOne("VenueAxe.Domain.Entities.Venue", "Venue")
                        .WithMany("WaiverTemplates")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingLanes");

                    b.Navigation("LaneSessions");

                    b.Navigation("Waivers");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.GameMatch", b =>
                {
                    b.Navigation("Throws");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Lane", b =>
                {
                    b.Navigation("BookingLanes");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.LaneSession", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("VenueAxe.Domain.Entities.Venue", b =>
                {
                    b.Navigation("BookingConfig");

                    b.Navigation("Bookings");

                    b.Navigation("Lanes");

                    b.Navigation("WaiverTemplates");

                    b.Navigation("Waivers");
                });
#pragma warning restore 612, 618
        }
    }
}
